// Entries view: import the DraftKings entries export for the loaded slate, see every entry against
// the rulebook (rules it breaks or "none"), its construction, the duplication estimate, and write a
// thesis per entry before lock. Data comes from server/entries.mjs; this file only draws it.
import { $, $$, esc } from "../app/ui.mjs";

const pc = v => v == null || isNaN(v) ? "—" : (+v).toFixed(0) + "%";
const nice = id => id.replace(/_/g, " ");
export function initEntries(S) { S.ent = S.ent || { data: null, dir: null, filter: "all", sort: "n" }; }

export async function renderEntries(main, ctx) {
  const { S, api, setMsg } = ctx; initEntries(S);
  if (!S.hub) { main.innerHTML = `<div class="empty">Load a slate first<small>Pick the slate and press Refresh on the Data Hub; entries are checked against that slate's players.</small></div>`; $("#bot").innerHTML = ""; return; }
  if (!S.ent.data || S.ent.dir !== S.hub.dir) { try { S.ent.data = await api(`/api/entries?dir=${encodeURIComponent(S.hub.dir)}`); S.ent.dir = S.hub.dir; } catch (e) { S.ent.data = { entries: [] }; } }
  const D = S.ent.data, s = D.summary, sd = S.hub.slate.type === "SHOWDOWN";
  const imp = `<label class="btn" style="cursor:pointer">${D.entries.length ? "Import another entries CSV" : "Import DK entries CSV"}<input type="file" id="fileEnt" accept=".csv" hidden></label>`;
  let html = `<div class="tool">${imp}<span class="hint">DraftKings → Lineups → Export, or Stokastic Entry Manager export. Checked against <b>${esc(S.hub.slate.name || S.hub.dir)}</b>${D.importedAt ? ` · imported ${new Date(D.importedAt).toLocaleString([], { month: "numeric", day: "numeric", hour: "numeric", minute: "2-digit" })}${D.source ? " from " + esc(D.source) : ""}` : ""}${D.rulesDerived ? ` · rulebook ${esc(D.rulesDerived)}` : ""}</span><div class="grow"></div>
    ${D.entries.length ? `<div class="pos">${[["all", "All"], ["FAIL", "Fail"], ["warn", "Warn"], ["ok", "Clean"], ["nothesis", "No thesis"]].map(([k, l]) => `<button data-filter="${k}" aria-selected="${S.ent.filter === k}">${l}</button>`).join("")}</div>` : ""}</div>`;
  if (!D.entries.length) { html += `<div class="empty">No entries imported for this slate<small>Export your entries from DraftKings (Lineups → Export to CSV) and import the file here. Downloads are not watched for entry files, only projections.</small></div>`; main.innerHTML = html; wire(main, ctx); $("#bot").innerHTML = ""; return; }
  const simOn = !!D.sim;
  // late swap mode: live points for started players, swaps for the open slots
  if (S.ent.late) { renderLate(main, ctx, D); return; }
  // you vs winners' profile for this format and tier (data/reports/winners-profile-nfl.json)
  if (S.ent.profile === undefined) { try { S.ent.profile = await api("/api/winners-profile"); } catch { S.ent.profile = null; } }
  html += `<div class="kpi">${[["Entries", s.lineups], ["Contests", s.contests], ["Fees", "$" + s.fees.toLocaleString()], ["Clean", s.ok], ["Warn", s.warn], ["Fail", s.fail], ["No thesis", s.noThesis], ["Dup risk", s.dupHigh], ["Avg own", s.avgOwn == null ? "—" : s.avgOwn + "%"], ["Avg chalk", s.avgChalk ?? "—"], ["Avg left", s.avgLeft == null ? "—" : "$" + s.avgLeft], ...(simOn ? [["Sim +all", s.simPositive ?? 0]] : [])].map(([k, v]) => `<div class="box"><div class="k">${k}</div><div class="v">${v}</div></div>`).join("")}
    <div class="box" style="display:flex;align-items:center;gap:10px"><button class="btn${simOn ? " sec" : ""}" id="runSim"${S.ent.simBusy ? " disabled" : ""}>${S.ent.simBusy ? "Simulating…" : simOn ? "Re-run 4-source sim" : "Run 4-source sim"}</button>${simOn ? `<span class="hint">${D.sim.sources.map(x => ({ stk: "Stokastic", etr: "ETR", blick: "Blick", mkt: "Market" }[x] || x)).join(" · ")} · field ${D.sim.fieldN.toLocaleString()} · ${new Date(D.sim.at).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })} · ${(D.sim.ms / 1000).toFixed(0)}s</span>` : `<span class="hint">ROI under each projection source against a generated field; fills the sim rule</span>`}</div>
    <div class="box" style="display:flex;align-items:center;gap:10px"><button class="btn sec" id="lateSwap"${S.ent.lateBusy ? " disabled" : ""}>${S.ent.lateBusy ? "Pulling live…" : "Late swap"}</button><span class="hint">live points for started players, swaps for open slots</span></div></div>
    ${profileRow(S, D)}`;
  let rows = D.entries.filter(e => S.ent.filter === "all" || (S.ent.filter === "nothesis" ? e.ok && !e.thesis : e.verdict === S.ent.filter));
  if (simOn) rows = rows.slice().sort((a, b) => ((b.sim ? b.sim.worst : -1e9) - (a.sim ? a.sim.worst : -1e9)));
  const SRC = { stk: "S", etr: "E", blick: "B", mkt: "M" };
  const simCell = e => { if (!e.sim) return `<span class="mini">${esc(e.simError || "—")}</span>`; const s = e.sim; return `<div class="simc">${s.sources.map(k => `<span class="${s[k].roi > 0 ? "up" : "dn"}" title="${esc({ stk: "Stokastic", etr: "ETR", blick: "Blick", mkt: "Market" }[k])}: ${s[k].roi}% ±${s[k].se}, top-10% ${s[k].t10}%, ${(100 * s[k].pct).toFixed(0)}th pct of field">${SRC[k]} ${s[k].roi > 0 ? "+" : ""}${s[k].roi.toFixed(0)}</span>`).join(" ")}<br><b class="${s.worst > 0 ? "up" : "dn"}">worst ${s.worst > 0 ? "+" : ""}${s.worst.toFixed(0)}%</b> <span class="mini">${s.agree}/${s.sources.length} agree · ${(100 * s.pctMed).toFixed(0)}th pct</span></div>`; };
  const chip = (v) => `<span class="vchip ${v === "ok" ? "g" : v === "FAIL" ? "r" : v === "warn" ? "y" : "m"}">${v === "ok" ? "clean" : v || "unmatched"}</span>`;
  const lu = e => `<div class="lu">${e.players.map(p => `<span class="ps">${esc(p.slot)}</span><b${p.inj && !/active/i.test(p.inj) ? ' style="color:#ffb4b4" title="' + esc(p.inj) + '"' : ""}>${esc(p.name)}</b><span class="mini"> ${pc(p.own)}</span>`).join('<span class="sep">|</span>')}</div>`;
  const rulesBox = e => { const fails = e.checks.filter(c => c.pass === false), unk = e.checks.filter(c => c.pass == null); return `<div class="rules">${fails.length ? fails.map(c => `<div class="${c.hard ? "hard" : "soft"}" title="${esc(c.rule)}">✗ ${esc(nice(c.id))} <span class="mini">${esc(c.detail)}</span></div>`).join("") : `<div class="none">none</div>`}${unk.length ? `<div class="unk">? ${unk.map(c => esc(nice(c.id))).join(", ")}</div>` : ""}</div>`; };
  const build = e => sd ? `${esc(e.split)}${e.qb ? ` · ${esc(e.qb)}+${e.stackN}` : " · no QB"}` : `${e.qb ? esc(e.qb) + "+" + e.stackN : "no QB"}${e.bring ? " · bring" : ""} · ${e.teams} tm`;
  const dup = e => e.dup.meanDup == null ? `<span class="mini">n/a</span>` : `<span class="${e.dup.meanDup >= (sd ? 2 : 1) ? "gap dn" : ""}">${e.dup.meanDup}</span><span class="mini"> ${(100 * e.dup.pDup).toFixed(0)}%</span>`;
  html += `<div class="tw" style="max-height:none"><table><thead><tr><th class="na">#</th><th class="na">Verdict</th><th class="na">Contest</th><th class="na">Lineup</th><th class="na num">Left</th><th class="na num">Own</th><th class="na num">Chalk</th><th class="na">Build</th><th class="na num" title="expected copies in the field · chance of any copy">Dup</th>${simOn ? '<th class="na" title="ROI per source: S Stokastic, E ETR, B Blick, M market; worst of them; how many are positive; percentile among field lineups">Sim ROI</th>' : ""}<th class="na">Rules broken</th><th class="na">Thesis</th></tr></thead><tbody>
    ${rows.map(e => e.ok ? `<tr><td>${e.n + 1}</td><td>${chip(e.verdict)}</td><td class="hint" style="white-space:normal;max-width:150px;font-size:11px">${esc(e.contest.replace(/^NFL (Showdown )?/, "").slice(0, 44))}<br><b>$${e.fee}</b>${e.contestN ? ` · ${e.contestN.toLocaleString()} field` : ""}</td><td>${lu(e)}</td><td class="num">$${e.left.toLocaleString()}</td><td class="num">${e.own.toFixed(0)}%</td><td class="num">${e.chalk}</td><td class="hint">${build(e)}</td><td class="num">${dup(e)}</td>${simOn ? `<td>${simCell(e)}</td>` : ""}<td>${rulesBox(e)}</td><td><textarea class="thesis" data-id="${esc(e.entryId || e.sig)}" rows="2" placeholder="Game + what must happen">${esc(e.thesis || "")}</textarea></td></tr>`
      : `<tr><td>${e.n + 1}</td><td>${chip(null)}</td><td class="hint">${esc(e.contest.slice(0, 40))}</td><td colspan="${simOn ? 9 : 8}" class="hint">not in this slate's players: ${esc(e.missing.join(", "))}</td></tr>`).join("")}</tbody></table></div>`;
  html += `<div style="padding:12px 16px 4px"><b style="font-size:12.5px">Exposure</b> <span class="hint">entries · share of your entries · projected ownership · over-exposure in points · captain count</span></div>
    <div class="tw" style="max-height:40vh"><table><thead><tr><th class="na">Player</th><th class="na">Team</th><th class="na">Pos</th><th class="na num">Entries</th><th class="na num">Share</th><th class="na num">Own</th><th class="na num">Over</th>${sd ? '<th class="na num">CPT</th>' : ""}</tr></thead><tbody>
    ${D.exposure.slice(0, 40).map(x => `<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.team)}</td><td>${esc(x.pos)}</td><td class="num">${x.n}</td><td class="num">${x.pct}%</td><td class="num">${pc(x.own)}</td><td class="num">${x.delta == null ? "—" : `<span class="${x.delta > 40 ? "gap dn" : ""}">${x.delta > 0 ? "+" : ""}${x.delta}</span>`}</td>${sd ? `<td class="num">${x.cpt}</td>` : ""}</tr>`).join("")}</tbody></table></div>`;
  main.innerHTML = html; wire(main, ctx);
  $("#bot").innerHTML = `<div class="bot"><span class="hint">Hard rules in red are the ones DraftKings or the archive say never to break; soft rules in yellow are the kept rulebook. "?" needs the sim (next build). A thesis saves when you click away.</span></div>`;
}
function wire(main, ctx) {
  const { S, api, setMsg, render } = ctx;
  const inp = $("#fileEnt", main); if (inp) inp.addEventListener("change", async e => { const f = e.target.files[0]; if (!f) return; setMsg(`Checking ${f.name}…`);
    try { S.ent.data = await api(`/api/entries?dir=${encodeURIComponent(S.hub.dir)}&name=${encodeURIComponent(f.name)}`, { method: "POST", body: await f.text() }); S.ent.dir = S.hub.dir; const s = S.ent.data.summary; setMsg(`${s.matched} of ${s.lineups} entries matched · ${s.ok} clean, ${s.warn} warn, ${s.fail} fail${s.unmatched ? ` · ${s.unmatched} unmatched` : ""}`, s.fail > 0 || s.unmatched > 0); }
    catch (err) { setMsg("Import failed: " + err.message, true); } render(); });
  $$("[data-filter]", main).forEach(b => b.addEventListener("click", () => { S.ent.filter = b.getAttribute("data-filter"); render(); }));
  const late = $("#lateSwap", main); if (late) late.addEventListener("click", async () => { S.ent.lateBusy = true; render(); setMsg("Pulling live box scores and re-simulating with started players locked…");
    try { S.ent.late = await api(`/api/lateswap?dir=${encodeURIComponent(S.hub.dir)}`, { method: "POST" }); setMsg(`${S.ent.late.started.length} teams started, ${S.ent.late.locked} players locked`); } catch (err) { setMsg("Late swap failed: " + err.message, true); } S.ent.lateBusy = false; render(); });
  const back = $("#lateBack", main); if (back) back.addEventListener("click", () => { S.ent.late = null; render(); });
  const run = $("#runSim", main); if (run) run.addEventListener("click", async () => { S.ent.simBusy = true; render(); setMsg("Simulating every entry under each projection source…");
    try { S.ent.data = await api(`/api/sim?dir=${encodeURIComponent(S.hub.dir)}`, { method: "POST" }); const d = S.ent.data; setMsg(`Simulated ${d.summary.matched} entries under ${d.sim.sources.length} sources in ${(d.sim.ms / 1000).toFixed(0)}s · ${d.summary.simPositive} positive under every source`); }
    catch (err) { setMsg("Sim failed: " + err.message, true); } S.ent.simBusy = false; render(); });
  $$("textarea.thesis", main).forEach(t => t.addEventListener("change", async () => { try { await api(`/api/thesis?dir=${encodeURIComponent(S.hub.dir)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ entryId: t.getAttribute("data-id"), thesis: t.value }) }); const e = S.ent.data.entries.find(x => String(x.entryId || x.sig) === t.getAttribute("data-id")); if (e) e.thesis = t.value; S.ent.data.summary.noThesis = S.ent.data.entries.filter(x => x.ok && !x.thesis).length; setMsg("Thesis saved"); } catch (err) { setMsg("Thesis not saved: " + err.message, true); } }));
}
// you vs the winners' profile (top-1% lineups in pulled $20+ contests) for this format and fee tier
function profileRow(S, D) {
  const P = S.ent.profile, s = D.summary; if (!P || !P.formats || !s || !s.matched) return "";
  const sd = S.hub.slate.type === "SHOWDOWN", fmt = P.formats[sd ? "showdown" : "classic"]; if (!fmt) return "";
  const good = D.entries.filter(e => e.ok), fee = good.reduce((a, e) => a + e.fee, 0) / good.length, tier = fee < 100 ? "lo" : fee < 300 ? "mid" : "hi", t = fmt[tier] || fmt.all; if (!t || !t.winners) return "";
  const w = t.winners, f = t.field, m = k => +(good.reduce((a, e) => a + (k(e) || 0), 0) / good.length).toFixed(2);
  const you = { own: m(e => e.own), chalk: m(e => e.chalk), left: m(e => e.left), dup: m(e => e.dup && e.dup.pDup != null ? e.dup.pDup : 0), stack: m(e => e.stackN), bring: m(e => e.bring ? 1 : 0), split51: m(e => e.split === "5-1" ? 1 : 0) };
  const cols = sd ? [["Own sum", "own", v => v.toFixed(0) + "%"], ["Chalk", "chalk", v => v.toFixed(1)], ["Left", "left", v => "$" + Math.round(v)], ["5-1", "split51", v => (100 * v).toFixed(0) + "%"], ["Duplicated", "dup", v => (100 * v).toFixed(0) + "%"]] : [["Own sum", "own", v => v.toFixed(0) + "%"], ["Chalk", "chalk", v => v.toFixed(1)], ["Left", "left", v => "$" + Math.round(v)], ["QB stack", "stack", v => v.toFixed(1)], ["Bring-back", "bring", v => (100 * v).toFixed(0) + "%"], ["Duplicated", "dup", v => (100 * v).toFixed(0) + "%"]];
  return `<div style="padding:0 16px 8px"><table style="width:auto;font-size:11.5px"><thead><tr><th class="na" style="position:static">You vs winners (${sd ? "showdown" : "classic"}, ${tier === "lo" ? "$20-99" : tier === "mid" ? "$100-299" : "$300+"}, ${w.n} winning lineups)</th>${cols.map(c => `<th class="na num" style="position:static">${c[0]}</th>`).join("")}</tr></thead><tbody>
    <tr><td><b>Your entries</b></td>${cols.map(([, k, fn]) => `<td class="num"><b>${fn(you[k])}</b></td>`).join("")}</tr>
    <tr><td>Winners</td>${cols.map(([, k, fn]) => `<td class="num">${w[k] == null ? "—" : fn(w[k])}</td>`).join("")}</tr>
    <tr><td class="hint">Field</td>${cols.map(([, k, fn]) => `<td class="num hint">${f[k] == null ? "—" : fn(f[k])}</td>`).join("")}</tr></tbody></table></div>`;
}
// late swap table: locked players at live points, open slots with the best fits for the salary left
function renderLate(main, ctx, D) {
  const { S } = ctx, L = S.ent.late, pcs = v => v == null ? "—" : v.toFixed(0) + "%";
  let html = `<div class="tool"><button class="btn sec" id="lateBack">← Back to entries</button><span class="hint">live ${new Date(L.at).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })} · ${L.started.length} teams started · ${L.locked} players locked${L.sources.length ? " · re-simmed under " + L.sources.join(", ") : ""}</span><div class="grow"></div><button class="btn sec" id="lateSwap">⟳ Pull live again</button></div>
    <div class="kpi">${L.games.map(g => `<div class="box"><div class="k">${esc(g.away)}@${esc(g.home)}</div><div class="v" style="font-size:13px">${g.started ? `${g.score[g.away]}-${g.score[g.home]} <span class="mini">${esc(g.detail)}</span>` : `<span class="mini">${esc(g.detail)}</span>`}</div></div>`).join("")}</div>`;
  for (const e of L.entries) {
    html += `<div style="padding:10px 16px 2px"><b>${esc(e.contest.replace(/^NFL (Showdown )?/, "").slice(0, 60))}</b> <span class="hint">$${e.fee} · locked ${e.lockedPts} + open ${e.openProj} = <b>${e.total}</b> projected${e.sim ? ` · sim worst ${e.sim.worst > 0 ? "+" : ""}${e.sim.worst}% (${e.sim.agree}/${e.sim.sources.length})` : ""} · $${e.left.toLocaleString()} left</span></div>
      <div class="lu" style="padding:0 16px 6px">${e.players.map(p => `<span class="ps">${esc(p.slot)}</span><b style="${p.locked ? "color:var(--muted)" : ""}">${esc(p.name)}</b><span class="mini"> ${p.locked ? (p.final ? "final " : "live ") + p.pts : "proj " + p.proj}</span>`).join('<span class="sep">|</span>')}</div>`;
    if (e.swaps.length) html += `<div class="tw" style="max-height:none;padding:0 16px 8px"><table style="font-size:11.5px"><thead><tr><th class="na">Open slot</th><th class="na">Current</th><th class="na num">Proj</th><th class="na num">Own</th><th class="na num">Budget</th><th class="na">Best fits (proj · own · gain)</th></tr></thead><tbody>
      ${e.swaps.map(s => `<tr><td><b>${esc(s.slot)}</b></td><td>${esc(s.current)}</td><td class="num">${s.currentProj}</td><td class="num">${pcs(s.currentOwn)}</td><td class="num">$${s.budget.toLocaleString()}</td><td style="white-space:normal">${s.cands.map(c => `<span style="display:inline-block;margin:1px 10px 1px 0"><b>${esc(c.name)}</b> <span class="mini">${esc(c.team)} $${c.sal.toLocaleString()} · ${c.proj} · ${pcs(c.own)} · <span class="${c.gain > 0 ? "gap up" : "gap dn"}">${c.gain > 0 ? "+" : ""}${c.gain}</span>${c.inj ? " · " + esc(c.inj) : ""}</span></span>`).join("") || '<span class="mini">nothing fits</span>'}</td></tr>`).join("")}</tbody></table></div>`;
    else html += `<div class="hint" style="padding:0 16px 8px">every slot locked</div>`;
  }
  main.innerHTML = html; wire(main, ctx);
  $("#bot").innerHTML = `<div class="bot"><span class="hint">Swaps are ranked by the Lab projection and must fit the salary left; players listed Out, Doubtful or IR are excluded. Nothing here is written to the pre-lock record.</span></div>`;
}
