// Contest Generator view (Stokastic shape): Pool Size, Team Controls, Stack Type Exposures, Contest
// Archetype, Generate Lineups / Restore Last Pool; tabs Players (ownership vs pool exposure with
// boost arrows), Stacks (pool vs desired), Lineups & Ranker (projection rank x ownership rank);
// Simulate Lineups sends the pool to the Simulator. Data from server/contestsim.mjs.
import { $, $$, esc, download } from "../app/ui.mjs";

const pc = (v, d = 1) => v == null || isNaN(v) ? "—" : (+v).toFixed(d) + "%";
const diffS = v => v == null ? "—" : `<span class="${v >= 0 ? "diffpos" : "diffneg"}">${v >= 0 ? "+" : ""}${(+v).toFixed(1)}%</span>`;
const SRCN = { stk: "Stokastic", etr: "ETR", blick: "Blick", mkt: "Market" }, SRC1 = { stk: "S", etr: "E", blick: "B", mkt: "M" };
export function initGen(S) { S.gen = S.gen || { data: null, dir: null, busy: false, tab: "players", pos: "ALL", q: "", wP: 50, wO: 50, pop: null, cfg: { n: 1000, arch: "marquee", ownSrc: "avg", stacks: { 1: 45, 2: 41, 3: 5, bring: 62 }, boosts: {}, teamsRemoved: [], teamBoost: {} }, sort: { players: { k: "exp", d: 1 }, rank: { k: "ovr", d: -1 } } }; }

export async function renderGen(main, ctx) {
  const { S, api, setMsg, render } = ctx; initGen(S); const G = S.gen;
  if (!S.hub) { main.innerHTML = `<div class="empty">Load a slate first<small>Pick the slate and press Refresh on the Data Hub.</small></div>`; $("#bot").innerHTML = ""; return; }
  if (!G.data || G.dir !== S.hub.dir) { try { G.data = await api(`/api/field?dir=${encodeURIComponent(S.hub.dir)}`); } catch { G.data = { rows: [] }; } G.dir = S.hub.dir; G.contests = null; if (G.data.cfg) { G.cfg = Object.assign({}, G.cfg, G.data.cfg); G.cfg.cid = G.data.cfg.contest ? G.data.cfg.contest.cid : ""; } }
  if (!G.contests) { try { const c = await api(`/api/contests?dir=${encodeURIComponent(S.hub.dir)}`); G.contests = c.contests.filter(x => x.fee > 0 && x.field > 0 && x.field < 1e6).sort((a, b) => (b.prizePool || 0) - (a.prizePool || 0)).slice(0, 80); } catch { G.contests = []; } }
  if (S.pendingGenCid) { G.cfg.cid = S.pendingGenCid; const pc0 = G.contests.find(x => String(x.id) === String(S.pendingGenCid)); if (pc0) G.cfg.n = Math.min(20000, pc0.field); S.pendingGenCid = null; }
  const D = G.data, cfg = G.cfg, sd = S.hub.slate.type === "SHOWDOWN", teams = S.hub.slate.games.flatMap(g => g.split("@"));
  const fld = (label, inner) => `<div class="f"><label>${label}</label>${inner}</div>`;
  const head = `<div class="ctl gen">
    ${fld("Contest", `<select class="sel" id="fcid" style="min-width:240px"><option value="">(none: pick a pool size)</option>${G.contests.map(c => `<option value="${c.id}"${String(cfg.cid) === String(c.id) ? " selected" : ""}>$${c.fee} · ${c.field.toLocaleString()} · ${esc(c.name.replace(/^NFL (Showdown )?/, "").slice(0, 38))}</option>`).join("")}</select>`)}
    ${cfg.cid ? fld("Pool Size", `<div class="sized" title="the pool is built at the contest's size so duplicates and finishing ranks match the real room${(G.contests.find(c => String(c.id) === String(cfg.cid)) || {}).field > 20000 ? "; capped at 20,000" : ""}">${Math.min(20000, (G.contests.find(c => String(c.id) === String(cfg.cid)) || {}).field || cfg.n).toLocaleString()} <span class="mini">sized to contest</span></div>`) : fld("Pool Size", `<select class="sel" id="fn">${[250, 500, 1000, 1500, 2000, 5000, 10000, 20000].map(n => `<option value="${n}"${+cfg.n === n ? " selected" : ""}>${n.toLocaleString()}</option>`).join("")}</select>`)}
    ${fld("Ownership", `<select class="sel" id="fown"><option value="avg"${cfg.ownSrc === "avg" ? " selected" : ""}>vendor average</option>${["stk", "etr", "blick"].filter(s => S.hub.sources[{ stk: "stokastic", etr: "etr", blick: "blick" }[s]]).map(s => `<option value="${s}"${cfg.ownSrc === s ? " selected" : ""}>${{ stk: "Stokastic", etr: "ETR", blick: "Blick" }[s]}</option>`).join("")}<option value="all"${cfg.ownSrc === "all" ? " selected" : ""}>all sources (one field each)</option></select>`)}
    ${fld("Team Controls", `<div style="position:relative"><button class="btn sec" id="btnTeams">Team Controls${cfg.teamsRemoved.length || Object.keys(cfg.teamBoost).length ? " ✎" : ""}</button><div id="popTeams"></div></div>`)}
    ${sd ? "" : fld("Stack Type Exposures", `<div style="position:relative"><button class="btn sec" id="btnStacks">Stack Type Exposures ✎</button><div id="popStacks"></div></div>`)}
    <div class="f slider"><label>Contest Archetype</label><input type="range" id="farch" min="0" max="2" step="1" value="${{ low: 0, marquee: 1, high: 2 }[cfg.arch] ?? 1}"><div class="ticks"><span>Low Stakes</span><span>Marquee</span><span>High Stakes</span></div></div>
    <div class="f cta"><label>&nbsp;</label><button class="btn gen" id="fgo"${G.busy ? " disabled" : ""}>${G.busy ? "Generating…" : D.rows && D.rows.length ? "Regenerate Lineups ⟳" : "Generate Lineups"}</button></div>
    <div class="stamp">${D.at && D.cfg.contest ? `for $${D.cfg.contest.fee} · ${esc(D.cfg.contest.name.replace(/^NFL (Showdown )?/, "").slice(0, 40))}<br>` : ""}${D.at ? (D.all ? `${D.sources.length} fields of ${D.N.toLocaleString()} (${D.sources.map(s => SRCN[s]).join(", ")}) · ${esc(D.cfg.arch)} · ${D.union.toLocaleString()} distinct lineups across them · ${D.dupes} duplicates<br>generated` : `pool ${D.N.toLocaleString()} · ${esc(D.cfg.arch)} · ${esc(D.cfg.ownSrc)} ownership · ${D.dupes} duplicate lineups<br>generated`) + ` ${new Date(D.at).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })} in ${(D.ms / 1000).toFixed(1)}s` : "Fill out settings to start generating."}</div></div>`;
  $("#tabs").innerHTML = `<div class="tabs">${[["players", "Players"], ["stacks", "Stacks"], ["rank", "Lineups & Ranker", D.rows ? D.rows.length : ""]].map(([k, l, n]) => `<button class="tab" data-gtab="${k}" aria-selected="${G.tab === k}">${l}${n ? `<span class="n">${n.toLocaleString()}</span>` : ""}</button>`).join("")}</div>`;
  if (!D.rows || !D.rows.length) { main.innerHTML = head + `<div class="empty">Fill out settings to start generating.<small>Pool size, ownership source, team controls, stack exposures and archetype, then Generate Lineups.</small></div>`; $("#bot").innerHTML = ""; wire(main, ctx); return; }
  let body = "";
  if (G.tab === "players") {
    const rows = D.players.filter(p => (G.pos === "ALL" || p.pos.split("/")[0] === G.pos) && (!G.q || p.name.toLowerCase().includes(G.q.toLowerCase()))).map(p => Object.assign({}, p, { diff: +(p.exp - p.own).toFixed(1) }));
    const st = G.sort.players, sk = { name: p => p.name, pos: p => p.pos, team: p => p.team, own: p => p.own, exp: p => p.exp, diff: p => p.diff, cown: p => p.cown, cexp: p => p.cexp }[st.k] || (p => p.exp);
    const all = D.all ? D.sources : [], skf = all.includes(st.k) ? (p => p.by[st.k] ?? 0) : sk;
    rows.sort((a, b) => { const x = skf(a), y = skf(b); return (typeof x === "string" ? x.localeCompare(y) : x - y) * -st.d; });
    const th = (k, l, cls = "", title = "") => `<th class="${cls}" data-psort="${k}" title="${esc(title)}">${l}${st.k === k ? `<span class="ar">${st.d > 0 ? "▼" : "▲"}</span>` : ""}</th>`;
    body = `<div class="tool"><div class="search">🔍 <input id="gq" placeholder="Search players" value="${esc(G.q)}"></div><div class="pos">${["ALL", "QB", "RB", "WR", "TE", "K", "DST"].map(p => `<button data-gpos="${p}" aria-selected="${G.pos === p}">${p}</button>`).join("")}</div><div class="grow"></div>${D.all ? `<span class="hint">Pool Exposure is the average across the ${all.length} fields; each source's own field beside it</span>` : ""}<button class="btn ghost" id="gexp">⬇ Export</button></div>
      <div class="tw"><table><thead><tr>${th("name", "Name", "stl")}${th("pos", "Pos.")}${th("team", "Team")}<th class="na">Opp</th>${th("own", "Ownership", "num")}${th("exp", "Pool Exposure", "num")}${th("diff", "Difference", "num")}${all.map(s => th(s, SRC1[s], "num", SRCN[s] + " field exposure")).join("")}${sd ? th("cown", "CPT Own", "num") + th("cexp", "CPT Exposure", "num") : ""}<th class="na ctr">Boost Ownership</th></tr></thead><tbody>
      ${rows.map(p => `<tr><td class="stl"><b>${esc(p.name)}</b></td><td>${esc(p.pos)}</td><td><span class="tm"><i></i>${esc(p.team)}</span></td><td>${esc(p.opp || "")}</td><td class="num">${pc(p.own)}</td><td class="num">${pc(p.exp)}</td><td class="num">${diffS(p.diff)}</td>${all.map(s => `<td class="num">${pc(p.by[s])}</td>`).join("")}${sd ? `<td class="num">${pc(p.cown)}</td><td class="num">${pc(p.cexp)}</td>` : ""}<td class="ctr"><span class="boost"><button data-boost="${esc(p.name)}|1" title="the field rosters him more">▲</button><button data-boost="${esc(p.name)}|-1" title="the field rosters him less">▼</button></span>${p.boost ? ` <span class="hint">${p.boost > 0 ? "+" : ""}${p.boost}</span>` : ""}</td></tr>`).join("")}</tbody></table></div>`;
  } else if (G.tab === "stacks") {
    body = `<div class="tool"><span class="hint">${sd ? "Captain position and team split in the pool" : "Stack types in the pool against the desired exposures"}</span></div><div class="tw"><table><thead><tr><th class="na">Stack Types</th><th class="na num">Pool Exposure</th>${sd ? "" : '<th class="na num">Desired Exposure</th><th class="na num">Difference</th>'}</tr></thead><tbody>
      ${D.stackRows.map(r => `<tr><td><b>${esc(r.type)}</b></td><td class="num">${pc(r.exp)}</td>${sd ? "" : `<td class="num">${r.desired == null ? "—" : r.desired + "%"}</td><td class="num">${r.diff == null ? "—" : diffS(r.diff)}</td>`}</tr>`).join("")}</tbody></table></div>`;
  } else {
    const w = (G.wP + G.wO) || 1, rows = D.rows.map(r => Object.assign({}, r, { ovr: +((G.wP * r.pr + G.wO * r.or) / w).toFixed(0) }));
    const st = G.sort.rank, sk = { pr: r => r.pr, or: r => r.or, ovr: r => r.ovr, proj: r => r.proj, own: r => r.own, sal: r => r.sal, dupes: r => r.dupes, from: r => (r.from || []).length }[st.k] || (r => r.ovr);
    rows.sort((a, b) => (sk(a) - sk(b)) * -st.d);
    const page = rows.slice(0, 300);
    const wt = (k, label) => `${label} <span class="wt"><button class="m" data-w="${k}|-10">−</button><span>${G[k]}%</span><button class="p" data-w="${k}|10">+</button></span>`;
    const th = (k, l, cls = "", title = "") => `<th class="${cls}" data-rsort="${k}" title="${esc(title)}">${l}${st.k === k ? `<span class="ar">${st.d > 0 ? "▼" : "▲"}</span>` : ""}</th>`;
    body = `<div class="tool"><span class="hint">Overall rank blends the projection rank and the ownership rank by the weights; the top of the list is the field's most obvious lineups.${D.all ? " Built by shows which sources' fields contain the lineup; dupes are its copies across all of them." : ""} First 300 of ${rows.length.toLocaleString()} shown; export for all.</span><div class="grow"></div><button class="btn ghost" id="gexp">⬇ Export</button></div>
      <div class="tw"><table><thead><tr>${th("pr", wt("wP", "Proj. Rank"), "num")}${th("or", wt("wO", "Own. Rank"), "num")}${th("ovr", "Overall Rank", "num")}${th("proj", "Lineup Proj", "num")}${th("own", "Total Ownership", "num")}${th("sal", "Salary", "num")}<th class="na">Stack Type</th>${th("dupes", "Dupes", "num")}${D.all ? th("from", "Built by", "ctr", "sources whose field built this lineup") : ""}<th class="na">Lineup</th></tr></thead><tbody>
      ${page.map(r => `<tr><td class="num">${r.pr.toLocaleString()}</td><td class="num">${r.or.toLocaleString()}</td><td class="num"><b>${r.ovr.toLocaleString()}</b></td><td class="num">${r.proj.toFixed(1)}</td><td class="num">${pc(r.own)}</td><td class="num">$${r.sal.toLocaleString()}</td><td class="ctr hint">${esc(r.type)}</td><td class="num">${r.dupes}</td>${D.all ? `<td class="ctr" title="${(r.from || []).map(s => SRCN[s]).join(", ")}">${(r.from || []).map(s => SRC1[s]).join(" ")}</td>` : ""}<td><div class="lu">${r.names.map(n => `<b>${esc(n)}</b>`).join('<span class="sep">|</span>')}</div></td></tr>`).join("")}</tbody></table></div>`;
  }
  main.innerHTML = head + body;
  $("#bot").innerHTML = `<div class="bot"><span class="hint">Boost arrows move the field's ownership, not your exposure. Regenerate after projection or ownership updates, pool size or archetype changes.</span><div class="grow"></div><button class="btn next" id="toSim">Simulate Lineups</button></div>`;
  wire(main, ctx);
}
function wire(main, ctx) {
  const { S, api, setMsg, render } = ctx, G = S.gen, cfg = G.cfg;
  $$("#tabs .tab").forEach(b => b.addEventListener("click", () => { G.tab = b.getAttribute("data-gtab"); render(); }));
  const fn = $("#fn"); if (fn) fn.addEventListener("change", e => { cfg.n = +e.target.value; });
  const fc = $("#fcid"); if (fc) fc.addEventListener("change", e => { cfg.cid = e.target.value; const c = G.contests.find(x => String(x.id) === String(cfg.cid)); if (c) { cfg.n = Math.min(20000, c.field); setMsg(`Pool will be built at ${cfg.n.toLocaleString()} lineups to match the contest; Generate to rebuild`); } render(); });
  const fo = $("#fown"); if (fo) fo.addEventListener("change", e => { cfg.ownSrc = e.target.value; });
  const fa = $("#farch"); if (fa) fa.addEventListener("change", e => { cfg.arch = ["low", "marquee", "high"][+e.target.value]; });
  const go = $("#fgo"); if (go) go.addEventListener("click", async () => { G.busy = true; render(); setMsg(cfg.ownSrc === "all" ? `Generating a ${cfg.n.toLocaleString()}-lineup field per source…` : `Generating a ${cfg.n.toLocaleString()}-lineup field…`); try { G.data = await api(`/api/field?dir=${encodeURIComponent(S.hub.dir)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(cfg) }); setMsg(G.data.all ? `${G.data.sources.length} fields of ${G.data.N.toLocaleString()} generated in ${(G.data.ms / 1000).toFixed(1)}s, ${G.data.union.toLocaleString()} distinct lineups` : `Field of ${G.data.N.toLocaleString()} generated in ${(G.data.ms / 1000).toFixed(1)}s, ${G.data.dupes} duplicates`); } catch (e) { setMsg("Generate failed: " + e.message, true); } G.busy = false; render(); });
  const ts = $("#toSim"); if (ts) ts.addEventListener("click", () => { S.sim = S.sim || {}; S.sim.useField = true; S.view = "sim"; render(); });
  const q = $("#gq"); if (q) q.addEventListener("input", e => { G.q = e.target.value; render(); setTimeout(() => { const i = $("#gq"); if (i) { i.focus(); i.setSelectionRange(i.value.length, i.value.length); } }, 0); });
  $$("[data-gpos]", main).forEach(b => b.addEventListener("click", () => { G.pos = b.getAttribute("data-gpos"); render(); }));
  $$("th[data-psort]", main).forEach(h => h.addEventListener("click", () => { const k = h.getAttribute("data-psort"); G.sort.players = G.sort.players.k === k ? { k, d: -G.sort.players.d } : { k, d: 1 }; render(); }));
  $$("th[data-rsort]", main).forEach(h => h.addEventListener("click", () => { const k = h.getAttribute("data-rsort"); G.sort.rank = G.sort.rank.k === k ? { k, d: -G.sort.rank.d } : { k, d: k === "proj" || k === "own" || k === "sal" || k === "dupes" ? 1 : -1 }; render(); }));
  $$("[data-boost]", main).forEach(b => b.addEventListener("click", () => { const [name, d] = b.getAttribute("data-boost").split("|"), k = name.toLowerCase().replace(/[.'`’]/g, "").replace(/-/g, " ").replace(/\s+/g, " ").trim().replace(/\s+(jr|sr|ii|iii|iv)$/, ""); cfg.boosts[k] = (cfg.boosts[k] || 0) + (+d); if (!cfg.boosts[k]) delete cfg.boosts[k]; const p = G.data.players.find(x => x.name === name); if (p) p.boost = cfg.boosts[k] || 0; setMsg("Ownership boost noted; regenerate to rebuild the field with it"); render(); }));
  $$("[data-w]", main).forEach(b => b.addEventListener("click", () => { const [k, d] = b.getAttribute("data-w").split("|"); G[k] = Math.max(0, Math.min(100, G[k] + (+d))); render(); }));
  const ex = $("#gexp"); if (ex) ex.addEventListener("click", () => { if (G.tab === "players") download(`field-players-${S.hub.dir}.csv`, ["Name,Pos,Team,Opp,Ownership,Pool Exposure,Difference"].concat(G.data.players.map(p => [p.name, p.pos, p.team, p.opp, p.own, p.exp, (p.exp - p.own).toFixed(1)].join(","))).join("\n")); else download(`field-${S.hub.dir}.csv`, ["Proj Rank,Own Rank,Lineup Proj,Total Ownership,Salary,Stack Type,Dupes,Lineup"].concat(G.data.rows.map(r => [r.pr, r.or, r.proj, r.own, r.sal, `"${r.type}"`, r.dupes, `"${r.names.join(" | ")}"`].join(","))).join("\n")); });
  // team controls popover
  const bt = $("#btnTeams"); if (bt) bt.addEventListener("click", () => { G.pop = G.pop === "teams" ? null : "teams"; pops(main, ctx); });
  const bs = $("#btnStacks"); if (bs) bs.addEventListener("click", () => { G.pop = G.pop === "stacks" ? null : "stacks"; pops(main, ctx); });
  pops(main, ctx);
}
function pops(main, ctx) {
  const { S, setMsg } = ctx, G = S.gen, cfg = G.cfg, teams = S.hub.slate.games.flatMap(g => g.split("@"));
  const pt = $("#popTeams"), ps = $("#popStacks"); if (pt) pt.innerHTML = ""; if (ps) ps.innerHTML = "";
  if (G.pop === "teams" && pt) {
    pt.innerHTML = `<div class="pop" style="min-width:320px"><h4>Team Controls</h4><div class="hint">Remove a team from the field, or scale how much the field rosters it.</div><table><thead><tr><th>Team</th><th>In field</th><th>Ownership ×</th></tr></thead><tbody>${teams.map(t => `<tr><td><b>${esc(t)}</b></td><td><input type="checkbox" data-trm="${t}"${cfg.teamsRemoved.includes(t) ? "" : " checked"}></td><td><input class="txt" style="width:60px" data-tb="${t}" value="${cfg.teamBoost[t] ?? 1}"></td></tr>`).join("")}</tbody></table><div style="margin-top:8px;display:flex;gap:8px"><button class="btn" id="tApply">Apply</button><button class="btn ghost" id="tReset">Reset</button></div></div>`;
    $("#tApply").addEventListener("click", () => { cfg.teamsRemoved = $$("[data-trm]", pt).filter(c => !c.checked).map(c => c.getAttribute("data-trm")); cfg.teamBoost = {}; $$("[data-tb]", pt).forEach(i => { const v = +i.value; if (v && v !== 1) cfg.teamBoost[i.getAttribute("data-tb")] = v; }); G.pop = null; pops(main, ctx); setMsg("Team controls saved; regenerate to apply"); });
    $("#tReset").addEventListener("click", () => { cfg.teamsRemoved = []; cfg.teamBoost = {}; G.pop = null; pops(main, ctx); });
  }
  if (G.pop === "stacks" && ps) {
    const st = cfg.stacks, tot = [1, 2, 3].reduce((s, k) => s + (+st[k] || 0), 0);
    ps.innerHTML = `<div class="pop"><h4>Stack Type Exposures</h4><div class="hint">Share of the field with each QB stack; the rest is unstacked. Bring-back is the share of stacked lineups that add an opponent.</div><table><thead><tr><th>Stack Type</th><th>Desired Exposure</th></tr></thead><tbody>${[["1", "QB + 1"], ["2", "QB + 2"], ["3", "QB + 3"], ["bring", "Bring-back"]].map(([k, l]) => `<tr><td><b>${l}</b></td><td><span class="step"><button class="m" data-ns="${k}|-5">−</button><input data-nsv="${k}" value="${+st[k] || 0}">%<button class="p" data-ns="${k}|5">+</button></span></td></tr>`).join("")}</tbody></table><div class="tot"><span>Stacked total</span><span>${tot}%</span></div><div style="margin-top:8px;display:flex;gap:8px"><button class="btn" id="sApply">Apply</button><button class="btn ghost" id="sDef">Defaults</button></div></div>`;
    $$("[data-ns]", ps).forEach(b => b.addEventListener("click", () => { const [k, d] = b.getAttribute("data-ns").split("|"); st[k] = Math.max(0, (+st[k] || 0) + (+d)); pops(main, ctx); }));
    $$("[data-nsv]", ps).forEach(i => i.addEventListener("change", () => { st[i.getAttribute("data-nsv")] = Math.max(0, +i.value || 0); pops(main, ctx); }));
    $("#sApply").addEventListener("click", () => { G.pop = null; pops(main, ctx); setMsg("Stack exposures saved; regenerate to apply"); });
    $("#sDef").addEventListener("click", () => { cfg.stacks = { 1: 45, 2: 41, 3: 5, bring: 62 }; pops(main, ctx); });
  }
}
