// Review view: every graded entry across the season (data/reports/entries-ledger-nfl.json from
// bench/grade-entries-nfl.mjs): ROI by verdict, by rule broken, by how many sim sources agreed,
// by tag; and the ledger with the thesis next to the result and a tag per entry
// (rule broken / rule wrong / variance). Buttons grade now and run the nightly reports now.
import { $, $$, esc } from "../app/ui.mjs";

const pc = v => v == null || isNaN(v) ? "—" : (+v).toFixed(0) + "%";
const money = v => v == null ? "—" : "$" + Math.round(v).toLocaleString();
const chip = v => `<span class="vchip ${v === "ok" ? "g" : v === "FAIL" ? "r" : v === "warn" ? "y" : "m"}">${v === "ok" ? "clean" : v}</span>`;
const TAGS = ["", "rule broken", "rule wrong", "variance"];

export async function renderReview(main, ctx) {
  const { S, api, setMsg, render } = ctx; S.rev = S.rev || { data: null, busy: "", filter: "all" };
  if (!S.rev.data) { try { S.rev.data = await api("/api/ledger"); } catch (e) { S.rev.data = { ledger: [] }; } }
  const D = S.rev.data, L = D.ledger || [];
  let html = `<div class="tool"><button class="btn" id="gradeNow"${S.rev.busy ? " disabled" : ""}>${S.rev.busy === "grade" ? "Grading…" : "Grade entries now"}</button><button class="btn sec" id="nightlyNow"${S.rev.busy ? " disabled" : ""}>${S.rev.busy === "nightly" ? "Running…" : "Run nightly reports now"}</button>
    <span class="hint">${D.built ? `ledger built ${new Date(D.built).toLocaleString([], { month: "numeric", day: "numeric", hour: "numeric", minute: "2-digit" })} for ${esc(D.user || "")}` : "no graded entries yet: import entries before lock, grade after the games"}</span><div class="grow"></div>
    ${L.length ? `<div class="pos">${[["all", "All"], ["ok", "Clean"], ["warn", "Warn"], ["FAIL", "Fail"], ["untagged", "Untagged"]].map(([k, l]) => `<button data-rf="${k}" aria-selected="${S.rev.filter === k}">${l}</button>`).join("")}</div>` : ""}</div>`;
  if (!L.length) { html += `<div class="empty">Nothing graded yet<small>Entries you import on the Entries tab get graded once their contests run (nightly at 04:30, or press Grade entries now).</small></div>`; main.innerHTML = html; wire(main, ctx); $("#bot").innerHTML = ""; return; }
  html += `<div class="kpi">${[["Graded entries", D.entries], ["Fees", money(D.fees)], ["Won", money(D.won)], ["ROI", pc(D.roi)]].map(([k, v]) => `<div class="box"><div class="k">${k}</div><div class="v">${v}</div></div>`).join("")}</div>`;
  const small = (title, obj, cols) => `<div class="box" style="flex:1;min-width:240px"><div class="k">${title}</div><table style="font-size:11.5px;margin-top:4px"><thead><tr>${cols.map(c => `<th class="na" style="position:static;padding:4px 6px">${c}</th>`).join("")}</tr></thead><tbody>${Object.entries(obj || {}).map(([k, v]) => `<tr><td style="padding:3px 6px"><b>${esc(k)}</b></td><td class="num" style="padding:3px 6px">${v.n}</td><td class="num" style="padding:3px 6px"><span class="${v.roi > 0 ? "gap up" : "gap dn"}">${pc(v.roi)}</span></td>${v.roiNot != null ? `<td class="num" style="padding:3px 6px">${pc(v.roiNot)}</td>` : v.cash != null ? `<td class="num" style="padding:3px 6px">${pc(v.cash)}</td>` : ""}</tr>`).join("")}</tbody></table></div>`;
  html += `<div class="kpi">${small("By verdict before lock", D.byVerdict, ["verdict", "n", "ROI", "cash"])}${small("By rule broken (ROI when broken vs not)", D.byRule, ["rule", "n", "ROI", "not broken"])}${small("By sim sources agreeing", D.bySimAgree, ["agree", "n", "ROI"])}${small("By your tag", D.byTag, ["tag", "n", "ROI"])}</div>`;
  const rows = L.filter(x => S.rev.filter === "all" || (S.rev.filter === "untagged" ? !x.tag : x.verdict === S.rev.filter));
  html += `<div class="tw" style="max-height:none"><table><thead><tr><th class="na">Date</th><th class="na">Contest</th><th class="na num">Fee</th><th class="na">Verdict</th><th class="na">Rules broken</th><th class="na">Sim</th><th class="na num">Dup est</th><th class="na num">Finish</th><th class="na num">ROI</th><th class="na num" title="where the lineup sat in Stokastic's post-contest sim ranking">Sim pct</th><th class="na">Thesis</th><th class="na">Tag</th></tr></thead><tbody>
    ${rows.map(x => `<tr><td class="mini">${esc(x.date)}</td><td style="white-space:normal;max-width:220px"><b>${esc(x.contest.replace(/^NFL (Showdown )?/, "").slice(0, 50))}</b><br><span class="mini">${esc(x.lineup.join(", "))}</span></td><td class="num">$${x.fee}</td><td>${chip(x.verdict)}</td><td class="rules" style="min-width:120px">${x.broken.length ? x.broken.map(r => `<div class="soft">✗ ${esc(r.replace(/_/g, " "))}</div>`).join("") : '<div class="none">none</div>'}</td><td class="mini">${x.sim ? `worst ${x.sim.worst > 0 ? "+" : ""}${x.sim.worst}% · ${x.sim.agree}/${x.sim.sources} · ${(100 * x.sim.pctMed).toFixed(0)}th` : "—"}</td><td class="num">${x.dup == null ? "—" : x.dup}</td><td class="num">${x.result.fin.toLocaleString()} / ${x.result.N.toLocaleString()}${x.result.dup ? `<br><span class="mini">${x.result.dup} copies</span>` : ""}</td><td class="num"><span class="${x.result.roi > 0 ? "gap up" : "gap dn"}">${pc(100 * x.result.roi)}</span><br><span class="mini">${money(x.result.won)}</span></td><td class="num">${(100 * x.result.simPct).toFixed(0)}th</td><td class="hint" style="white-space:normal;max-width:220px;font-size:11px">${esc(x.thesis) || '<span class="mini">no thesis written</span>'}</td><td><select class="sel tag" data-dir="${esc(x.dir)}" data-id="${esc(x.entryId)}" style="min-height:26px;padding:2px 22px 2px 6px">${TAGS.map(t => `<option value="${t}"${(x.tag || "") === t ? " selected" : ""}>${t || "untagged"}</option>`).join("")}</select></td></tr>`).join("")}</tbody></table></div>`;
  main.innerHTML = html; wire(main, ctx);
  $("#bot").innerHTML = `<div class="bot"><span class="hint">Three tags only: rule broken (you knew), rule wrong (the rulebook needs a look), variance (clean entry, lost anyway). Change a rule only when "rule wrong" piles up.</span></div>`;
}
function wire(main, ctx) {
  const { S, api, setMsg, render } = ctx;
  const g = $("#gradeNow", main); if (g) g.addEventListener("click", async () => { S.rev.busy = "grade"; render(); setMsg("Grading entries against pulled contests…"); try { S.rev.data = await api("/api/grade", { method: "POST" }); setMsg((S.rev.data.out || "graded").split("\n").pop()); } catch (e) { setMsg("Grade failed: " + e.message, true); } S.rev.busy = ""; render(); });
  const n = $("#nightlyNow", main); if (n) n.addEventListener("click", async () => { S.rev.busy = "nightly"; render(); setMsg("Running the nightly reports (a few minutes)…"); try { const r = await api("/api/nightly", { method: "POST" }); setMsg(r.running ? "Nightly already running" : `Nightly done in ${(r.ms / 1000).toFixed(0)}s: ` + r.log.map(l => `${l.ok ? "✓" : "✗"} ${l.script.replace("bench/", "")}`).join("  "), r.log && r.log.some(l => !l.ok)); S.rev.data = null; } catch (e) { setMsg("Nightly failed: " + e.message, true); } S.rev.busy = ""; render(); });
  $$("[data-rf]", main).forEach(b => b.addEventListener("click", () => { S.rev.filter = b.getAttribute("data-rf"); render(); }));
  $$("select.tag", main).forEach(s => s.addEventListener("change", async () => { try { await api(`/api/tag?dir=${encodeURIComponent(s.getAttribute("data-dir"))}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ entryId: s.getAttribute("data-id"), tag: s.value }) }); const x = S.rev.data.ledger.find(y => String(y.entryId) === s.getAttribute("data-id") && y.dir === s.getAttribute("data-dir")); if (x) x.tag = s.value; setMsg("Tag saved (the summary by tag updates at the next grade)"); } catch (e) { setMsg("Tag not saved: " + e.message, true); } }));
}
