// Simulator view: generate candidate lineups from a chosen projection source, simulate every one
// under all four sources, and compare where each source ranks them. Rows carry the same rules
// summary as Entries. Checked rows export as a DraftKings upload CSV. Data from server/gensim.mjs.
import { $, $$, esc, download } from "../app/ui.mjs";

const pc = v => v == null || isNaN(v) ? "—" : (+v).toFixed(0) + "%";
const nice = id => id.replace(/_/g, " ");
const SRC = { stk: "S", etr: "E", blick: "B", mkt: "M" }, LONG = { stk: "Stokastic", etr: "ETR", blick: "Blick", mkt: "Market", lab: "Lab blend", cons: "Consensus", avg: "vendor average" };
export function initSim(S) { S.sim = S.sim || { data: null, dir: null, busy: false, contests: null, cfg: { src: "lab", ownSrc: "avg", n: 50, rand: 18, maxExp: 60, minUniq: 1, force: "", exclude: "", cid: "" }, sort: { k: "meanRank", d: 1 }, sel: new Set(), open: new Set() }; }

export async function renderSim(main, ctx) {
  const { S, api, setMsg, render } = ctx; initSim(S); const G = S.sim;
  if (!S.hub) { main.innerHTML = `<div class="empty">Load a slate first<small>Pick the slate and press Refresh on the Data Hub.</small></div>`; $("#bot").innerHTML = ""; return; }
  if (!G.data || G.dir !== S.hub.dir) { try { G.data = await api(`/api/gen?dir=${encodeURIComponent(S.hub.dir)}`); } catch { G.data = { rows: [] }; } G.dir = S.hub.dir; G.sel = new Set(); if (G.data.cfg) Object.assign(G.cfg, G.data.cfg); if (G.data.contest && G.data.contest.cid) G.cfg.cid = String(G.data.contest.cid); }
  if (!G.contests) { try { const c = await api(`/api/contests?dir=${encodeURIComponent(S.hub.dir)}`); G.contests = c.contests.slice(0, 60); } catch { G.contests = []; } }
  const D = G.data, cfg = G.cfg, srcOpts = ["lab", "cons", "stk", "etr", "blick", "mkt"].filter(s => s === "lab" || s === "cons" || S.hub.sources[{ stk: "stokastic", etr: "etr", blick: "blick", mkt: "market" }[s]]);
  const fld = (label, inner) => `<div class="f"><label>${label}</label>${inner}</div>`;
  let html = `<div class="ctl gen">
    ${fld("Contest", `<select class="sel" id="gcid" style="min-width:300px"><option value="">(custom: $20, 10,000 field)</option>${G.contests.map(c => `<option value="${c.id}"${String(cfg.cid) === String(c.id) ? " selected" : ""}>$${c.fee} · ${c.field.toLocaleString()} · ${esc(c.name.replace(/^NFL (Showdown )?/, "").slice(0, 48))}</option>`).join("")}</select>`)}
    ${fld("Build from", `<select class="sel" id="gsrc">${srcOpts.map(s => `<option value="${s}"${cfg.src === s ? " selected" : ""}>${LONG[s]}</option>`).join("")}</select>`)}
    ${fld("Ownership", `<select class="sel" id="gown"><option value="avg"${cfg.ownSrc === "avg" ? " selected" : ""}>vendor average</option>${["stk", "etr", "blick"].filter(s => S.hub.sources[{ stk: "stokastic", etr: "etr", blick: "blick" }[s]]).map(s => `<option value="${s}"${cfg.ownSrc === s ? " selected" : ""}>${LONG[s]}</option>`).join("")}</select>`)}
    ${fld("Lineups", `<input class="txt" id="gn" type="number" min="1" max="300" value="${cfg.n}" style="width:70px">`)}
    ${fld("Random %", `<input class="txt" id="grand" type="number" min="0" max="60" value="${cfg.rand}" style="width:70px">`)}
    ${fld("Max exp %", `<input class="txt" id="gexp" type="number" min="5" max="100" value="${cfg.maxExp}" style="width:70px">`)}
    ${fld("Min uniq", `<input class="txt" id="guniq" type="number" min="0" max="6" value="${cfg.minUniq}" style="width:60px">`)}
    ${fld("Force", `<input class="txt" id="gforce" placeholder="names, comma" value="${esc(cfg.force)}" style="width:150px">`)}
    ${fld("Exclude", `<input class="txt" id="gexcl" placeholder="names, comma" value="${esc(cfg.exclude)}" style="width:150px">`)}
    <div class="f cta"><label>&nbsp;</label><button class="btn gen" id="gorun"${G.busy ? " disabled" : ""}>${G.busy ? "Building + simming…" : "Generate + sim"}</button></div>
    <div class="stamp">${D.at ? `last run ${new Date(D.at).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })} · ${(D.ms / 1000).toFixed(0)}s · built from ${LONG[D.src] || D.src} with ${LONG[D.ownSrc] || D.ownSrc} ownership` : "nothing generated yet"}</div></div>`;
  if (!D.rows || !D.rows.length) { main.innerHTML = html + `<div class="empty">No candidates yet<small>Pick a contest, press Generate + sim. Lineups build from the chosen projections and the vendors' ownership, then every one is simulated under Stokastic, ETR, Blick and the market.</small></div>`; wire(main, ctx); $("#bot").innerHTML = ""; return; }
  const s = D.summary, srcs = D.sources;
  html += `<div class="kpi">${[["Candidates", s.n], ["Clean", s.ok], ["Warn", s.warn], ["Fail", s.fail], ["+ under all", s.allPositive], ["Contest", `$${D.contest.fee} · ${D.contest.N.toLocaleString()}`], ["Selected", G.sel.size]].map(([k, v]) => `<div class="box"><div class="k">${k}</div><div class="v">${v}</div></div>`).join("")}
    <div class="box" style="display:flex;align-items:center;gap:10px"><button class="btn sec" id="gexport"${G.sel.size ? "" : " disabled"}>Export ${G.sel.size || ""} selected as DK upload CSV</button><button class="btn ghost" id="gselclean">select all clean</button><button class="btn ghost" id="gselnone">clear</button></div></div>`;
  const SORT = { meanRank: e => e.sim.meanRank, spread: e => e.sim.rankSpread, worst: e => -e.sim.worst, agree: e => -e.sim.agree, own: e => -e.own, left: e => -e.left, chalk: e => -e.chalk, dup: e => e.dup && e.dup.meanDup != null ? e.dup.meanDup : 1e9, rules: e => -(e.checks.filter(c => c.pass === true).length - 3 * e.checks.filter(c => c.pass === false && c.hard).length), lab: e => -e.lab, n: e => e.n };
  for (const k of srcs) SORT["r_" + k] = e => e.sim[k].rank;
  const sk = SORT[G.sort.k] || SORT.meanRank, rows = D.rows.slice().sort((a, b) => (sk(a) - sk(b)) * G.sort.d || a.n - b.n);
  const th = (k, label, cls = "", title = "") => `<th class="${cls}" data-gsort="${k}" title="${esc(title)}">${label}${G.sort.k === k ? `<span class="ar">${G.sort.d > 0 ? "▲" : "▼"}</span>` : ""}</th>`;
  const chip = v => `<span class="vchip ${v === "ok" ? "g" : v === "FAIL" ? "r" : "y"}">${v === "ok" ? "clean" : v}</span>`;
  const lu = e => `<div class="lu">${e.players.map(p => `<span class="ps">${esc(p.slot)}</span><b>${esc(p.name)}</b><span class="mini"> ${pc(p.own)}</span>`).join('<span class="sep">|</span>')}</div>`;
  const rules = e => { const lab = e.checks.filter(c => (c.source || "lab") === "lab"), fails = lab.filter(c => c.pass === false), hard = fails.filter(c => c.hard).length, others = e.checks.filter(c => c.source && c.source !== "lab"), ok = e.checks.filter(c => c.pass === true).length, tot = e.checks.filter(c => c.pass != null).length, open = G.open.has(e.n);
    return `<div class="rules"><div class="rsum" data-gopen="${e.n}"><b>${ok}/${tot}</b> · ${fails.length ? `<span class="${hard ? "hard" : "soft"}">✗ ${fails.length}${hard ? ` (${hard} hard)` : ""}</span>` : '<span class="none">clean</span>'}${others.length ? ` <span class="mini">· ETR/Slate ${others.filter(c => c.pass === true).length}/${others.filter(c => c.pass != null).length}</span>` : ""} <span class="mini">${open ? "▴" : "▾"}</span></div><div class="rdet"${open ? "" : " hidden"}>${e.checks.filter(c => c.pass === false).map(c => `<div class="${c.hard ? "hard" : c.source && c.source !== "lab" ? "etrmiss" : "soft"}" title="${esc(c.rule)}">✗ ${esc(nice(c.id))} <span class="mini">${esc(c.detail)}</span></div>`).join("")}<div class="unk">✓ ${e.checks.filter(c => c.pass === true).map(c => esc(nice(c.id))).join(", ")}</div></div></div>`; };
  const simCells = e => srcs.map(k => `<td class="num" title="${LONG[k]}: ROI ${e.sim[k].roi}% ±${e.sim[k].se}, ${(100 * e.sim[k].pct).toFixed(0)}th pct of field"><b>#${e.sim[k].rank}</b><br><span class="${e.sim[k].roi > 0 ? "gap up" : "gap dn"}" style="font-size:10.5px">${e.sim[k].roi > 0 ? "+" : ""}${e.sim[k].roi.toFixed(0)}%</span></td>`).join("");
  html += `<div class="tw" style="max-height:none"><table><thead><tr><th class="na"></th>${th("n", "#")}<th class="na">Verdict</th><th class="na">Lineup</th>${th("lab", "Lab", "num", "Lab-blend projection")}${th("left", "Left", "num")}${th("own", "Own", "num")}${th("chalk", "Chalk", "num")}<th class="na">Build</th>${th("dup", "Dup", "num", "expected copies; sorts fewest first")}${srcs.map(k => th("r_" + k, SRC[k] + " rank", "num", LONG[k] + " rank among the candidates, with its ROI")).join("")}${th("meanRank", "Mean rank", "num", "average rank across the sources")}${th("spread", "Spread", "num", "best rank minus worst rank: high means the sources disagree")}${th("worst", "Worst", "num", "lowest ROI across the sources")}${th("agree", "Agree", "num", "sources with positive ROI")}${th("rules", "Rules", "", "rules followed; click a row for detail")}</tr></thead><tbody>
    ${rows.map(e => `<tr><td><input type="checkbox" data-gsel="${e.n}"${G.sel.has(e.n) ? " checked" : ""}></td><td>${e.n + 1}</td><td>${chip(e.verdict)}</td><td>${lu(e)}</td><td class="num">${e.lab.toFixed(1)}</td><td class="num">$${e.left.toLocaleString()}</td><td class="num">${e.own.toFixed(0)}%</td><td class="num">${e.chalk}</td><td class="hint">${esc(e.split)}${e.qb ? ` · ${esc(e.qb)}+${e.stackN}` : ""}${e.bring ? " · bring" : ""}</td><td class="num">${e.dup.meanDup == null ? "—" : e.dup.meanDup}</td>${simCells(e)}<td class="num"><b>${e.sim.meanRank}</b></td><td class="num">${e.sim.rankSpread}</td><td class="num"><span class="${e.sim.worst > 0 ? "gap up" : "gap dn"}">${e.sim.worst > 0 ? "+" : ""}${e.sim.worst.toFixed(0)}%</span></td><td class="num">${e.sim.agree}/${srcs.length}</td><td>${rules(e)}</td></tr>`).join("")}</tbody></table></div>`;
  html += `<div style="padding:12px 16px 4px"><b style="font-size:12.5px">Exposure across the candidates</b></div><div class="tw" style="max-height:30vh"><table><thead><tr><th class="na">Player</th><th class="na">Team</th><th class="na">Pos</th><th class="na num">Lineups</th><th class="na num">Share</th><th class="na num">Own</th><th class="na num">Over</th></tr></thead><tbody>${D.exposure.slice(0, 30).map(x => `<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.team)}</td><td>${esc(x.pos)}</td><td class="num">${x.n}</td><td class="num">${x.pct}%</td><td class="num">${pc(x.own)}</td><td class="num">${x.delta == null ? "—" : (x.delta > 0 ? "+" : "") + x.delta}</td></tr>`).join("")}</tbody></table></div>`;
  main.innerHTML = html; wire(main, ctx);
  $("#bot").innerHTML = `<div class="bot"><span class="hint">Ranks are each source's order of these candidates by simulated ROI. A low mean rank with a small spread is a lineup every source likes; a big spread is a bet on one vendor. Check rows and export to upload on DraftKings, then export DK's entries file into the Entries tab.</span></div>`;
}
function wire(main, ctx) {
  const { S, api, setMsg, render } = ctx, G = S.sim;
  const read = () => { G.cfg.cid = $("#gcid", main).value; G.cfg.src = $("#gsrc", main).value; G.cfg.ownSrc = $("#gown", main).value; G.cfg.n = +$("#gn", main).value; G.cfg.rand = +$("#grand", main).value; G.cfg.maxExp = +$("#gexp", main).value; G.cfg.minUniq = +$("#guniq", main).value; G.cfg.force = $("#gforce", main).value; G.cfg.exclude = $("#gexcl", main).value; };
  $$("#gcid,#gsrc,#gown,#gn,#grand,#gexp,#guniq,#gforce,#gexcl", main).forEach(el => el.addEventListener("change", read));
  const run = $("#gorun", main); if (run) run.addEventListener("click", async () => { read(); G.busy = true; render(); setMsg(`Building ${G.cfg.n} lineups from ${G.cfg.src} and simulating under every source…`);
    try { G.data = await api(`/api/gen?dir=${encodeURIComponent(S.hub.dir)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(G.cfg) }); G.sel = new Set(); G.open = new Set(); setMsg(`${G.data.summary.n} candidates in ${(G.data.ms / 1000).toFixed(0)}s · ${G.data.summary.allPositive} positive under every source · ${G.data.summary.ok} clean`); }
    catch (e) { setMsg("Generate failed: " + e.message, true); } G.busy = false; render(); });
  $$("th[data-gsort]", main).forEach(h => h.addEventListener("click", () => { const k = h.getAttribute("data-gsort"); G.sort = G.sort.k === k ? { k, d: -G.sort.d } : { k, d: 1 }; render(); }));
  $$("[data-gsel]", main).forEach(cb => cb.addEventListener("change", () => { const n = +cb.getAttribute("data-gsel"); if (cb.checked) G.sel.add(n); else G.sel.delete(n); const b = $("#gexport", main); if (b) { b.disabled = !G.sel.size; b.textContent = `Export ${G.sel.size || ""} selected as DK upload CSV`; } }));
  $$(".rsum[data-gopen]", main).forEach(el => el.addEventListener("click", () => { const n = +el.getAttribute("data-gopen"), det = el.nextElementSibling; if (G.open.has(n)) G.open.delete(n); else G.open.add(n); if (det) det.hidden = !G.open.has(n); const a = el.querySelector(".mini:last-child"); if (a) a.textContent = G.open.has(n) ? "▴" : "▾"; }));
  const sc = $("#gselclean", main); if (sc) sc.addEventListener("click", () => { G.sel = new Set(G.data.rows.filter(e => e.verdict === "ok").map(e => e.n)); render(); });
  const sn = $("#gselnone", main); if (sn) sn.addEventListener("click", () => { G.sel = new Set(); render(); });
  const ex = $("#gexport", main); if (ex) ex.addEventListener("click", () => {
    const sd = G.data.format === "nfl_sd", head = sd ? ["CPT", "FLEX", "FLEX", "FLEX", "FLEX", "FLEX"] : ["QB", "RB", "RB", "WR", "WR", "WR", "TE", "FLEX", "DST"];
    const lines = [head.join(",")].concat(G.data.rows.filter(e => G.sel.has(e.n)).map(e => e.players.map(p => p.dkId ? `${p.name} (${p.dkId})` : p.name).map(v => /,/.test(v) ? `"${v}"` : v).join(",")));
    download(`DK-upload-${G.data.dir}.csv`, lines.join("\n") + "\n"); setMsg(`${G.sel.size} lineups exported; upload on DraftKings (Lineups → Upload), then export the entries file into the Entries tab`);
  });
}
